SELECT E.F_NAME, E.L_NAME, JH.START_DATE, J.JOB_TITLE FROM EMPLOYEES E JOIN JOB_HISTORY JH ON E.EMP_ID = JH.EMPL_ID JOIN JOBS J ON JH.JOBS_ID = J.JOB_IDENT WHERE E.DEP_ID = 5;
SELECT E.EMP_ID, E.L_NAME, E.DEP_ID, D.DEP_NAME FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D ON E.DEP_ID = D.DEPT_ID_DEP;
--2b
SELECT E.EMP_ID, E.L_NAME, E.DEP_ID, D.DEP_NAME FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D ON E.DEP_ID = D.DEPT_ID_DEP WHERE YEAR(E.B_DATE) < 1980;
--ALT 2B
SELECT E.EMP_ID, E.L_NAME, E.DEP_ID, D.DEP_NAME FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEP_ID = D.DEPT_ID_DEP WHERE YEAR(E.B_DATE) < 1980;
--2C
SELECT E.EMP_ID, E.L_NAME, E.DEP_ID, D.DEP_NAME FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D ON E.DEP_ID = D.DEPT_ID_DEP AND YEAR(E.B_DATE) < 1980;
SELECT E.F_NAME, E.L_NAME, D.DEP_NAME FROM EMPLOYEES E FULL JOIN DEPARTMENTS D ON E.DEP_ID = D.DEPT_ID_DEP;
SELECT E.F_NAME, E.L_NAME, D.DEPT_ID_DEP, D.DEP_NAME FROM EMPLOYEES E FULL JOIN DEPARTMENTS D ON E.DEP_ID = D.DEPT_ID_DEP AND E.SEX = 'M';